// Self-contained emoji dataset for the project icon picker.
// No network/CDN — keeps the app local-first (nothing phones home).
// Each entry: the literal emoji + space-separated search keywords.

export interface EmojiEntry {
    e: string; // the literal emoji character
    k: string; // search keywords (lowercase, space-separated)
}

export interface EmojiCategory {
    name: string;
    tab: string; // emoji shown on the category tab
    emojis: EmojiEntry[];
}

type Raw = [string, string];
const cat = (name: string, tab: string, raw: Raw[]): EmojiCategory => ({
    name,
    tab,
    emojis: raw.map(([e, k]) => ({ e, k })),
});

export const EMOJI_CATEGORIES: EmojiCategory[] = [
    cat('Smileys & Emotion', '😀', [
        ['😀', 'grinning face smile happy'],
        ['😃', 'grinning big eyes happy smile'],
        ['😄', 'grinning smiling eyes happy joy'],
        ['😁', 'beaming grin smile happy'],
        ['😆', 'grinning squinting laugh haha'],
        ['😅', 'grinning sweat laugh relief'],
        ['🤣', 'rolling floor laughing rofl'],
        ['😂', 'joy tears laughing lol'],
        ['🙂', 'slight smile'],
        ['🙃', 'upside down silly'],
        ['😉', 'wink flirt'],
        ['😊', 'blush smile happy'],
        ['😇', 'innocent halo angel'],
        ['🥰', 'smiling hearts love adore'],
        ['😍', 'heart eyes love crush'],
        ['🤩', 'star struck excited amazed'],
        ['😘', 'kiss blowing love'],
        ['😋', 'savoring yum tasty tongue'],
        ['😛', 'tongue out playful'],
        ['😜', 'wink tongue silly'],
        ['🤪', 'zany goofy wild'],
        ['🤔', 'thinking hmm consider'],
        ['🤨', 'raised eyebrow skeptical'],
        ['😐', 'neutral meh'],
        ['😏', 'smirk sly'],
        ['😒', 'unamused annoyed'],
        ['🙄', 'eye roll annoyed'],
        ['😬', 'grimace awkward'],
        ['😌', 'relieved calm content'],
        ['😔', 'pensive sad'],
        ['😴', 'sleeping zzz tired'],
        ['😪', 'sleepy tired'],
        ['🤤', 'drooling'],
        ['😷', 'mask sick face'],
        ['🤒', 'thermometer sick ill'],
        ['🤢', 'nauseated sick'],
        ['🤮', 'vomit sick'],
        ['🥵', 'hot heat sweating'],
        ['🥶', 'cold freezing'],
        ['😵', 'dizzy knocked out'],
        ['🤯', 'mind blown exploding'],
        ['🤠', 'cowboy hat'],
        ['🥳', 'party celebrate hat'],
        ['😎', 'cool sunglasses'],
        ['🤓', 'nerd geek glasses'],
        ['🧐', 'monocle inspect curious'],
        ['😕', 'confused'],
        ['😟', 'worried'],
        ['🙁', 'frown slight sad'],
        ['😮', 'open mouth surprised wow'],
        ['😲', 'astonished shocked'],
        ['🥺', 'pleading puppy eyes'],
        ['😢', 'crying sad tear'],
        ['😭', 'sobbing crying loud'],
        ['😱', 'screaming fear shocked'],
        ['😤', 'huffing triumph frustrated'],
        ['😡', 'angry rage mad'],
        ['😠', 'angry mad'],
        ['🤬', 'cursing swearing angry'],
        ['😈', 'devil smiling horns'],
        ['💀', 'skull death dead'],
        ['💩', 'poop pile'],
        ['🤡', 'clown'],
        ['👻', 'ghost boo'],
        ['👽', 'alien ufo'],
        ['🤖', 'robot bot ai'],
        ['😺', 'cat smile'],
        ['❤️', 'red heart love'],
        ['🧡', 'orange heart'],
        ['💛', 'yellow heart'],
        ['💚', 'green heart'],
        ['💙', 'blue heart'],
        ['💜', 'purple heart'],
        ['🖤', 'black heart'],
        ['🤍', 'white heart'],
        ['💔', 'broken heart'],
        ['💖', 'sparkling heart'],
        ['💯', 'hundred score perfect'],
    ]),
    cat('People & Body', '🧑', [
        ['👋', 'wave hello hi bye'],
        ['🤚', 'raised back hand'],
        ['✋', 'raised hand stop high five'],
        ['🖖', 'vulcan spock'],
        ['👌', 'ok perfect'],
        ['🤌', 'pinched fingers italian'],
        ['✌️', 'victory peace'],
        ['🤞', 'crossed fingers luck'],
        ['🤟', 'love you gesture'],
        ['🤘', 'rock horns'],
        ['🤙', 'call me hang loose'],
        ['👈', 'point left'],
        ['👉', 'point right'],
        ['👆', 'point up'],
        ['👇', 'point down'],
        ['☝️', 'index up one'],
        ['👍', 'thumbs up like good yes'],
        ['👎', 'thumbs down dislike no'],
        ['✊', 'raised fist'],
        ['👊', 'fist bump punch'],
        ['👏', 'clap applause'],
        ['🙌', 'raising hands celebrate'],
        ['🙏', 'pray please thanks namaste'],
        ['✍️', 'writing hand pen'],
        ['💅', 'nail polish manicure'],
        ['💪', 'muscle strong flex strength'],
        ['🦾', 'mechanical arm bionic'],
        ['🧠', 'brain mind smart think'],
        ['👀', 'eyes look watch'],
        ['👁', 'eye'],
        ['👶', 'baby infant'],
        ['🧒', 'child kid'],
        ['🧑', 'person adult'],
        ['👨', 'man'],
        ['👩', 'woman'],
        ['🧓', 'older person'],
        ['🧑‍🎓', 'student graduate learn'],
        ['🧑‍🏫', 'teacher professor educate'],
        ['🧑‍💻', 'developer coder programmer tech'],
        ['🧑‍🔬', 'scientist researcher lab'],
        ['🧑‍🎨', 'artist painter creative'],
        ['🧑‍🚀', 'astronaut space'],
        ['🧑‍⚕️', 'doctor nurse health medical'],
        ['🧑‍🍳', 'chef cook'],
        ['🦸', 'superhero hero'],
        ['🦹', 'supervillain villain'],
        ['🧙', 'mage wizard magic'],
        ['🧚', 'fairy'],
        ['🧛', 'vampire'],
        ['🧜', 'merperson mermaid'],
        ['🧝', 'elf'],
        ['🚶', 'walking pedestrian'],
        ['🏃', 'running run'],
        ['💃', 'dancing dance'],
        ['🕺', 'man dancing'],
        ['🧘', 'meditation yoga zen calm'],
        ['🏋️', 'weight lifting gym workout'],
        ['🤸', 'cartwheel gymnastics'],
        ['👮', 'police officer cop'],
        ['🕵️', 'detective spy investigate'],
        ['👷', 'construction worker builder'],
        ['🤴', 'prince royal'],
        ['👸', 'princess royal'],
        ['🥷', 'ninja'],
    ]),
    cat('Animals & Nature', '🐶', [
        ['🐶', 'dog puppy'],
        ['🐱', 'cat kitten'],
        ['🐭', 'mouse'],
        ['🐹', 'hamster'],
        ['🐰', 'rabbit bunny'],
        ['🦊', 'fox'],
        ['🐻', 'bear'],
        ['🐼', 'panda'],
        ['🐨', 'koala'],
        ['🐯', 'tiger'],
        ['🦁', 'lion'],
        ['🐮', 'cow'],
        ['🐷', 'pig'],
        ['🐸', 'frog'],
        ['🐵', 'monkey'],
        ['🐔', 'chicken'],
        ['🐧', 'penguin'],
        ['🐦', 'bird'],
        ['🦆', 'duck'],
        ['🦅', 'eagle'],
        ['🦉', 'owl wise'],
        ['🦇', 'bat'],
        ['🐺', 'wolf'],
        ['🐴', 'horse'],
        ['🦄', 'unicorn'],
        ['🐝', 'bee honey'],
        ['🐛', 'bug caterpillar'],
        ['🦋', 'butterfly'],
        ['🐌', 'snail'],
        ['🐞', 'ladybug'],
        ['🐜', 'ant'],
        ['🕷', 'spider'],
        ['🐢', 'turtle tortoise'],
        ['🐍', 'snake'],
        ['🦖', 'dinosaur trex'],
        ['🐙', 'octopus'],
        ['🦑', 'squid'],
        ['🦐', 'shrimp'],
        ['🦀', 'crab'],
        ['🐠', 'fish tropical'],
        ['🐬', 'dolphin'],
        ['🐳', 'whale'],
        ['🦈', 'shark'],
        ['🐘', 'elephant'],
        ['🦒', 'giraffe'],
        ['🐪', 'camel'],
        ['🐉', 'dragon'],
        ['🌵', 'cactus'],
        ['🎄', 'christmas tree'],
        ['🌲', 'evergreen tree pine'],
        ['🌳', 'tree'],
        ['🌴', 'palm tree'],
        ['🌱', 'seedling sprout grow'],
        ['🌿', 'herb plant'],
        ['☘️', 'shamrock clover'],
        ['🍀', 'four leaf clover luck'],
        ['🍂', 'fallen leaves autumn'],
        ['🍁', 'maple leaf'],
        ['🍄', 'mushroom'],
        ['🌾', 'wheat grain rice'],
        ['💐', 'bouquet flowers'],
        ['🌷', 'tulip'],
        ['🌹', 'rose'],
        ['🌺', 'hibiscus flower'],
        ['🌸', 'cherry blossom sakura'],
        ['🌻', 'sunflower'],
        ['🌼', 'blossom daisy flower'],
        ['🌞', 'sun face bright'],
        ['🌙', 'crescent moon night'],
        ['⭐', 'star favorite'],
        ['🌟', 'glowing star sparkle'],
        ['✨', 'sparkles shiny magic'],
        ['⚡', 'lightning bolt zap energy'],
        ['🔥', 'fire flame hot lit'],
        ['🌈', 'rainbow'],
        ['☀️', 'sun sunny weather'],
        ['☁️', 'cloud'],
        ['❄️', 'snowflake cold winter'],
        ['💧', 'droplet water'],
        ['🌊', 'wave ocean sea water'],
        ['🌍', 'earth globe world europe africa'],
        ['🪐', 'planet saturn space'],
    ]),
    cat('Food & Drink', '🍎', [
        ['🍎', 'apple red fruit'],
        ['🍏', 'green apple'],
        ['🍐', 'pear'],
        ['🍊', 'orange tangerine'],
        ['🍋', 'lemon'],
        ['🍌', 'banana'],
        ['🍉', 'watermelon'],
        ['🍇', 'grapes'],
        ['🍓', 'strawberry'],
        ['🫐', 'blueberries'],
        ['🍒', 'cherries'],
        ['🍑', 'peach'],
        ['🥭', 'mango'],
        ['🍍', 'pineapple'],
        ['🥥', 'coconut'],
        ['🥝', 'kiwi'],
        ['🍅', 'tomato'],
        ['🍆', 'eggplant aubergine'],
        ['🥑', 'avocado'],
        ['🥦', 'broccoli'],
        ['🥕', 'carrot'],
        ['🌽', 'corn'],
        ['🌶', 'hot pepper chili spicy'],
        ['🥔', 'potato'],
        ['🍞', 'bread'],
        ['🥐', 'croissant'],
        ['🧀', 'cheese'],
        ['🥚', 'egg'],
        ['🍳', 'cooking fried egg breakfast'],
        ['🥞', 'pancakes'],
        ['🥓', 'bacon'],
        ['🍔', 'hamburger burger'],
        ['🍟', 'fries chips'],
        ['🍕', 'pizza'],
        ['🌭', 'hot dog'],
        ['🥪', 'sandwich'],
        ['🌮', 'taco'],
        ['🌯', 'burrito'],
        ['🥗', 'salad healthy'],
        ['🍝', 'spaghetti pasta'],
        ['🍜', 'ramen noodles soup'],
        ['🍣', 'sushi'],
        ['🍱', 'bento box'],
        ['🍚', 'rice'],
        ['🍤', 'shrimp tempura fried'],
        ['🍦', 'ice cream soft serve'],
        ['🍩', 'donut doughnut'],
        ['🍪', 'cookie'],
        ['🎂', 'birthday cake'],
        ['🍰', 'cake slice dessert'],
        ['🧁', 'cupcake'],
        ['🍫', 'chocolate'],
        ['🍬', 'candy sweet'],
        ['🍭', 'lollipop'],
        ['🍿', 'popcorn'],
        ['🍯', 'honey'],
        ['🥛', 'milk glass'],
        ['☕', 'coffee tea hot drink'],
        ['🍵', 'tea green matcha'],
        ['🧃', 'juice box'],
        ['🥤', 'soda cup drink'],
        ['🍺', 'beer'],
        ['🍻', 'beers cheers'],
        ['🥂', 'champagne toast celebrate'],
        ['🍷', 'wine'],
        ['🍸', 'cocktail martini'],
        ['🍴', 'fork knife eat dining'],
        ['🍽', 'plate dining meal'],
    ]),
    cat('Travel & Places', '✈️', [
        ['🚗', 'car automobile drive'],
        ['🚕', 'taxi cab'],
        ['🚙', 'suv car'],
        ['🚌', 'bus'],
        ['🏎', 'race car fast'],
        ['🚓', 'police car'],
        ['🚑', 'ambulance'],
        ['🚒', 'fire engine truck'],
        ['🚚', 'delivery truck'],
        ['🚜', 'tractor farm'],
        ['🛴', 'scooter kick'],
        ['🚲', 'bicycle bike cycling'],
        ['🏍', 'motorcycle'],
        ['🚨', 'siren alert emergency'],
        ['🚀', 'rocket launch space startup'],
        ['🛸', 'ufo flying saucer'],
        ['🚁', 'helicopter'],
        ['✈️', 'airplane plane flight travel'],
        ['🛫', 'departure takeoff'],
        ['🛬', 'arrival landing'],
        ['🚂', 'train locomotive steam'],
        ['🚆', 'train'],
        ['🚇', 'metro subway underground'],
        ['🚊', 'tram'],
        ['🚝', 'monorail'],
        ['⛵', 'sailboat sail'],
        ['🚤', 'speedboat'],
        ['🛳', 'cruise ship passenger'],
        ['⚓', 'anchor'],
        ['⛽', 'fuel gas station'],
        ['🚦', 'traffic light'],
        ['🗺', 'map world'],
        ['🗿', 'moai statue'],
        ['🗽', 'statue liberty new york'],
        ['🗼', 'tower tokyo'],
        ['🏰', 'castle palace'],
        ['🏯', 'japanese castle'],
        ['🎡', 'ferris wheel'],
        ['🎢', 'roller coaster'],
        ['🎠', 'carousel merry go round'],
        ['⛲', 'fountain'],
        ['🏖', 'beach umbrella'],
        ['🏝', 'island tropical'],
        ['🏜', 'desert'],
        ['🌋', 'volcano'],
        ['⛰', 'mountain'],
        ['🏔', 'snow mountain peak'],
        ['🗻', 'mount fuji'],
        ['🏕', 'camping tent'],
        ['🏠', 'house home'],
        ['🏡', 'house garden home'],
        ['🏢', 'office building'],
        ['🏭', 'factory industry'],
        ['🏥', 'hospital medical'],
        ['🏦', 'bank'],
        ['🏨', 'hotel'],
        ['🏫', 'school education'],
        ['🏛', 'classical building museum government'],
        ['⛪', 'church'],
        ['🕌', 'mosque'],
        ['🛕', 'hindu temple'],
        ['🌅', 'sunrise'],
        ['🌃', 'night city stars'],
        ['🌉', 'bridge night'],
        ['🌌', 'milky way galaxy stars'],
    ]),
    cat('Activities', '⚽', [
        ['⚽', 'soccer football'],
        ['🏀', 'basketball'],
        ['🏈', 'american football'],
        ['⚾', 'baseball'],
        ['🥎', 'softball'],
        ['🎾', 'tennis'],
        ['🏐', 'volleyball'],
        ['🏉', 'rugby'],
        ['🥏', 'frisbee disc'],
        ['🎱', 'pool billiards 8 ball'],
        ['🏓', 'ping pong table tennis'],
        ['🏸', 'badminton'],
        ['🏒', 'hockey'],
        ['🏑', 'field hockey'],
        ['🥍', 'lacrosse'],
        ['🏏', 'cricket'],
        ['⛳', 'golf flag'],
        ['🪁', 'kite'],
        ['🏹', 'bow arrow archery'],
        ['🎣', 'fishing'],
        ['🥊', 'boxing glove'],
        ['🥋', 'martial arts karate'],
        ['⛸', 'ice skate'],
        ['🎿', 'ski'],
        ['🏂', 'snowboard'],
        ['🏄', 'surfing surf'],
        ['🏊', 'swimming swim'],
        ['🚣', 'rowing boat'],
        ['🧗', 'climbing rock'],
        ['🚴', 'cycling bike rider'],
        ['🏆', 'trophy win champion award'],
        ['🥇', 'gold medal first'],
        ['🥈', 'silver medal second'],
        ['🥉', 'bronze medal third'],
        ['🏅', 'medal sports'],
        ['🎖', 'military medal honor'],
        ['🎗', 'ribbon awareness'],
        ['🎫', 'ticket'],
        ['🎪', 'circus tent'],
        ['🤹', 'juggling'],
        ['🎭', 'theater drama masks arts'],
        ['🎨', 'art palette paint creative'],
        ['🎬', 'clapper film movie'],
        ['🎤', 'microphone sing karaoke'],
        ['🎧', 'headphones music audio'],
        ['🎼', 'music score sheet'],
        ['🎹', 'piano keyboard music'],
        ['🥁', 'drum'],
        ['🎷', 'saxophone'],
        ['🎺', 'trumpet'],
        ['🎸', 'guitar'],
        ['🎻', 'violin'],
        ['🎲', 'dice game board'],
        ['♟', 'chess pawn strategy'],
        ['🎯', 'dart target bullseye goal'],
        ['🎳', 'bowling'],
        ['🎮', 'game controller gaming videogame'],
        ['🕹', 'joystick arcade'],
        ['🧩', 'puzzle piece jigsaw'],
        ['🧸', 'teddy bear toy'],
    ]),
    cat('Objects', '💡', [
        ['⌚', 'watch time'],
        ['📱', 'phone mobile smartphone'],
        ['💻', 'laptop computer code'],
        ['⌨️', 'keyboard typing'],
        ['🖥', 'desktop computer monitor'],
        ['🖨', 'printer'],
        ['🖱', 'mouse computer'],
        ['💽', 'minidisk save'],
        ['💾', 'floppy disk save'],
        ['💿', 'cd disc'],
        ['📀', 'dvd disc'],
        ['📷', 'camera photo'],
        ['📹', 'video camera'],
        ['🎥', 'movie camera film'],
        ['📺', 'television tv'],
        ['📻', 'radio'],
        ['🎙', 'studio microphone podcast'],
        ['⏰', 'alarm clock time'],
        ['⏳', 'hourglass time wait'],
        ['📡', 'satellite dish signal'],
        ['🔋', 'battery power'],
        ['🔌', 'plug power electric'],
        ['💡', 'lightbulb idea bright'],
        ['🔦', 'flashlight torch'],
        ['🕯', 'candle'],
        ['💸', 'money flying cash spend'],
        ['💵', 'dollar money cash'],
        ['💰', 'money bag rich wealth'],
        ['💳', 'credit card payment'],
        ['💎', 'gem diamond jewel'],
        ['⚖️', 'scale balance justice law'],
        ['🧰', 'toolbox tools'],
        ['🔧', 'wrench tool fix'],
        ['🔨', 'hammer build'],
        ['🛠', 'hammer wrench tools build'],
        ['⚙️', 'gear settings cog'],
        ['🧱', 'brick wall'],
        ['🧲', 'magnet'],
        ['🧪', 'test tube chemistry science lab'],
        ['🧫', 'petri dish biology'],
        ['🧬', 'dna genetics biology'],
        ['🔬', 'microscope science research'],
        ['🔭', 'telescope astronomy stars'],
        ['📡', 'antenna satellite'],
        ['💊', 'pill medicine drug'],
        ['💉', 'syringe injection vaccine'],
        ['🩺', 'stethoscope doctor health'],
        ['🌡', 'thermometer temperature'],
        ['🦠', 'microbe virus germ'],
        ['🔑', 'key access'],
        ['🔒', 'lock secure private'],
        ['🔓', 'unlock open'],
        ['🛡', 'shield defense security'],
        ['🔭', 'telescope'],
        ['🎁', 'gift present box'],
        ['🎈', 'balloon party'],
        ['🎉', 'party popper celebrate tada'],
        ['🎊', 'confetti ball celebrate'],
        ['✉️', 'envelope mail email'],
        ['📦', 'package box parcel'],
        ['📫', 'mailbox'],
        ['📜', 'scroll document history ancient'],
        ['📄', 'page document file'],
        ['📊', 'bar chart data analytics'],
        ['📈', 'chart up growth trending'],
        ['📉', 'chart down decline'],
        ['📅', 'calendar date schedule'],
        ['📆', 'calendar tear off'],
        ['🗓', 'spiral calendar planner'],
        ['📋', 'clipboard tasks'],
        ['📁', 'folder file'],
        ['📂', 'open folder'],
        ['🗂', 'card index dividers organize'],
        ['📰', 'newspaper news'],
        ['📓', 'notebook'],
        ['📔', 'notebook decorative journal'],
        ['📒', 'ledger notebook'],
        ['📕', 'closed book red'],
        ['📗', 'green book'],
        ['📘', 'blue book'],
        ['📙', 'orange book'],
        ['📚', 'books library study reading learn'],
        ['📖', 'open book reading'],
        ['🔖', 'bookmark'],
        ['🔗', 'link chain url'],
        ['📐', 'triangle ruler geometry math'],
        ['📏', 'ruler measure'],
        ['🧮', 'abacus math count calculate'],
        ['📌', 'pushpin pin'],
        ['📍', 'location pin map'],
        ['✂️', 'scissors cut'],
        ['🖊', 'pen write'],
        ['🖋', 'fountain pen write'],
        ['✏️', 'pencil write edit'],
        ['📝', 'memo note write notes'],
        ['🔍', 'search magnify find zoom'],
        ['🔎', 'search right magnify'],
        ['🗝', 'old key'],
        ['🪙', 'coin money'],
        ['⏱', 'stopwatch timer'],
        ['🧭', 'compass navigation direction'],
        ['🔮', 'crystal ball fortune magic'],
        ['🎓', 'graduation cap mortarboard degree learn'],
        ['🩹', 'bandage plaster'],
        ['🧴', 'lotion bottle'],
        ['🧼', 'soap clean'],
        ['🪔', 'oil lamp diya'],
        ['🧯', 'fire extinguisher'],
    ]),
    cat('Symbols', '❤️', [
        ['❤️', 'red heart love'],
        ['💕', 'two hearts love'],
        ['💖', 'sparkling heart'],
        ['💯', 'hundred perfect score'],
        ['✅', 'check mark done complete green'],
        ['☑️', 'checkbox checked done'],
        ['✔️', 'check mark done yes'],
        ['❌', 'cross mark wrong no x'],
        ['⭕', 'circle red'],
        ['❗', 'exclamation important'],
        ['❓', 'question mark help'],
        ['‼️', 'double exclamation'],
        ['⚠️', 'warning caution alert'],
        ['🚫', 'prohibited no forbidden'],
        ['🔞', 'no under eighteen adult'],
        ['☢️', 'radioactive'],
        ['☣️', 'biohazard'],
        ['♻️', 'recycle eco green'],
        ['⚜️', 'fleur de lis'],
        ['🔰', 'beginner novice'],
        ['✳️', 'asterisk eight spoked'],
        ['❇️', 'sparkle'],
        ['™️', 'trademark'],
        ['©️', 'copyright'],
        ['®️', 'registered'],
        ['🔱', 'trident emblem'],
        ['⚛️', 'atom science physics'],
        ['🕉', 'om hindu'],
        ['✝️', 'cross christian'],
        ['☪️', 'star crescent islam'],
        ['☮️', 'peace'],
        ['☯️', 'yin yang balance'],
        ['♈', 'aries zodiac'],
        ['♉', 'taurus zodiac'],
        ['♊', 'gemini zodiac'],
        ['♋', 'cancer zodiac'],
        ['♌', 'leo zodiac'],
        ['♍', 'virgo zodiac'],
        ['♎', 'libra zodiac'],
        ['♏', 'scorpio zodiac'],
        ['♐', 'sagittarius zodiac'],
        ['♑', 'capricorn zodiac'],
        ['♒', 'aquarius zodiac'],
        ['♓', 'pisces zodiac'],
        ['🔔', 'bell notification alert'],
        ['🔕', 'mute bell off'],
        ['📣', 'megaphone announce'],
        ['💬', 'speech bubble chat comment'],
        ['💭', 'thought bubble think'],
        ['🗯', 'anger speech bubble'],
        ['♠️', 'spades card'],
        ['♣️', 'clubs card'],
        ['♥️', 'hearts card'],
        ['♦️', 'diamonds card'],
        ['🃏', 'joker card'],
        ['🔢', 'numbers 1234'],
        ['🔤', 'abc letters alphabet'],
        ['🔠', 'capital letters abcd'],
        ['#️⃣', 'hash number'],
        ['➕', 'plus add'],
        ['➖', 'minus subtract'],
        ['➗', 'divide division'],
        ['✖️', 'multiply times'],
        ['♾', 'infinity endless'],
        ['💲', 'dollar sign money'],
        ['➡️', 'arrow right'],
        ['⬅️', 'arrow left'],
        ['⬆️', 'arrow up'],
        ['⬇️', 'arrow down'],
        ['🔄', 'refresh sync cycle'],
        ['🔁', 'repeat loop'],
        ['▶️', 'play'],
        ['⏸', 'pause'],
        ['⏹', 'stop'],
        ['🔵', 'blue circle'],
        ['🔴', 'red circle'],
        ['🟢', 'green circle'],
        ['🟡', 'yellow circle'],
        ['🟠', 'orange circle'],
        ['🟣', 'purple circle'],
        ['⚫', 'black circle'],
        ['⚪', 'white circle'],
        ['🟥', 'red square'],
        ['🟩', 'green square'],
        ['🟦', 'blue square'],
        ['🟨', 'yellow square'],
        ['⬛', 'black square'],
        ['⬜', 'white square'],
        ['🔶', 'orange diamond'],
        ['🔷', 'blue diamond'],
    ]),
    cat('Flags', '🏁', [
        ['🏁', 'checkered flag finish race'],
        ['🚩', 'triangular flag marker'],
        ['🏳️', 'white flag'],
        ['🏴', 'black flag'],
        ['🏳️‍🌈', 'rainbow flag pride lgbt'],
        ['🏴‍☠️', 'pirate flag jolly roger'],
        ['🇺🇸', 'usa united states america flag'],
        ['🇬🇧', 'uk britain united kingdom england flag'],
        ['🇨🇦', 'canada flag'],
        ['🇦🇺', 'australia flag'],
        ['🇩🇪', 'germany flag deutschland'],
        ['🇫🇷', 'france flag'],
        ['🇪🇸', 'spain flag espana'],
        ['🇮🇹', 'italy flag'],
        ['🇵🇹', 'portugal flag'],
        ['🇳🇱', 'netherlands flag holland'],
        ['🇸🇪', 'sweden flag'],
        ['🇳🇴', 'norway flag'],
        ['🇩🇰', 'denmark flag'],
        ['🇫🇮', 'finland flag'],
        ['🇵🇱', 'poland flag'],
        ['🇬🇷', 'greece flag'],
        ['🇮🇪', 'ireland flag'],
        ['🇷🇺', 'russia flag'],
        ['🇺🇦', 'ukraine flag'],
        ['🇹🇷', 'turkey flag'],
        ['🇨🇳', 'china flag'],
        ['🇯🇵', 'japan flag'],
        ['🇰🇷', 'korea south flag'],
        ['🇮🇳', 'india flag'],
        ['🇧🇷', 'brazil flag'],
        ['🇲🇽', 'mexico flag'],
        ['🇦🇷', 'argentina flag'],
        ['🇿🇦', 'south africa flag'],
        ['🇸🇦', 'saudi arabia flag'],
        ['🇦🇪', 'uae emirates flag'],
        ['🇮🇱', 'israel flag'],
        ['🇪🇬', 'egypt flag'],
        ['🇳🇬', 'nigeria flag'],
        ['🇮🇩', 'indonesia flag'],
        ['🇹🇭', 'thailand flag'],
        ['🇻🇳', 'vietnam flag'],
        ['🇵🇭', 'philippines flag'],
        ['🇸🇬', 'singapore flag'],
        ['🇳🇿', 'new zealand flag'],
    ]),
];
